apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-streamer
  namespace: okd-streamer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-streamer
  template:
    metadata:
      labels:
        app: simple-streamer
    spec:
      # AWS ECR 프라이빗 이미지를 가져오기 위한 인증 키
      imagePullSecrets:
      - name: ecr-registry-key
      containers:
      - name: simple-streamer
        # 빌드 시 GitHub Actions가 이 태그 부분을 자동으로 업데이트하게 됩니다.
        image: 635014547592.dkr.ecr.us-east-1.amazonaws.com/jellyfin-media-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST
          value: "hybrid-demo-db.c4dqgm4aut3y.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          value: "12345678"
        - name: S3_BUCKET
          value: "hybrid-demo-video-bucket-jki-2026"
        - name: AWS_REGION
          value: "us-east-1"
        # S3 접근을 위한 IAM 키 (Secret에서 참조)
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
