apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-streamer
  namespace: okd-streamer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-streamer
  template:
    metadata:
      labels:
        app: simple-streamer
    spec:
      imagePullSecrets:
      - name: ecr-registry-key
      containers:
      - name: simple-streamer
        image: 635014547592.dkr.ecr.us-east-1.amazonaws.com/streamer:bc869a5a94a8bc14e4204e0f0b00c9b9de2e4f55
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST
          value: "hybrid-prod-db-2.c8bacacucmpz.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "videodb"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          value: "12345678"
        - name: S3_BUCKET
          value: "prod-video-bucket-idac-2026"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
        - name: PGSSLMODE
          value: "disable"
