apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-streamer
  namespace: streamer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-streamer
  template:
    metadata:
      labels:
        app: simple-streamer
    spec:
      # AWS ECR 접근을 위한 출입증 (나중에 oc 명령어로 만들 이름)
      imagePullSecrets:
      - name: ecr-registry-key
      containers:
      - name: simple-streamer
        # EKS팀이 빌드한 최신 ECR 이미지 주소
        image: 625572953167.dkr.ecr.us-east-1.amazonaws.com/simple_streamer:c900eed98d4f9dd8f54238313fbfaa5eba4bf20f
        ports:
        - containerPort: 8080 # 앱 포트에 맞게 수정 가능
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST
          value: "hybrid-demo-db.c4dqgm4aut3y.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASS
          value: "12345678"
        - name: S3_BUCKET
          value: "hybrid-demo-video-bucket-jki-2026"
        - name: AWS_REGION
          value: "us-east-1"
        # AWS 인증 키 (Secret에서 가져옴)
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key
