apiVersion: v1
kind: Service
metadata:
  name: simple-streamer-svc
  namespace: okd-streamer
spec:
  selector:
    app: simple-streamer
  ports:
    - name: http-port        # 이름을 추가했습니다.
      protocol: TCP
      port: 80
      targetPort: 8080
