apiVersion: v1
kind: Service
metadata:
  name: simple-streamer-svc
  namespace: okd-streamer
spec:
  selector:
    app: simple-streamer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
