apiVersion: v1
kind: Service
metadata:
  name: simple-streamer-svc
  namespace: okd-streamer
spec:
  # type: NodePort를 삭제하거나 ClusterIP로 변경 (Nginx가 라우터를 통해 들어가므로)
  selector:
    app: simple-streamer
  ports:
  - name: 8096-tcp
    protocol: TCP
    port: 8096          # 서비스 포트
    targetPort: 8080    # 앱 내부 포트
